const C='haru-v49',F=['./','index.html','manifest.json','icon-180.png','icon-512.png',
 'assets/b_bf1.webp','assets/b_bf2.webp','assets/b_bf3.webp','assets/b_bf4.webp','assets/b_bf5.webp','assets/b_bf6.webp','assets/b_sp1.webp','assets/b_sp2.webp','assets/b_sp3.webp','assets/b_sp4.webp','assets/b_sp5.webp','assets/u_panel.webp','assets/u_i_todo.webp','assets/u_i_moon.webp','assets/u_i_book.webp','assets/u_i_gear.webp','assets/u_i_send.webp','assets/u_input.webp','assets/u_chk0.webp','assets/u_chk1.webp','assets/bg.jpg','assets/box_c.webp','assets/u_lock.webp','assets/bg_pub.jpg','assets/box_o.webp','assets/c_base.webp','assets/o_half.webp','assets/o_worry.webp','assets/o_smile.webp','assets/o_closed.webp','assets/o_talk.webp','assets/o_nod.webp','assets/o_sleepy.webp','assets/o_side.webp','assets/o_surprised.webp','assets/o_pleased.webp','assets/p_show.webp','assets/p_think.webp','assets/p_read.webp','assets/p_wave.webp','assets/p_tea.webp','assets/p_shy.webp','assets/p_bow.webp','assets/p_pout.webp','assets/q_show_talk.webp','assets/q_wave_blink.webp','assets/q_pout_blink.webp','assets/q_tea_blink.webp','assets/q_read_blink.webp','assets/q_think_blink.webp','assets/k_base.webp','assets/k_half.webp','assets/k_closed.webp','assets/k_happy.webp','assets/k_surprised.webp','assets/k_think.webp','assets/k_sad.webp','assets/k_pleased.webp','assets/k_wave.webp','assets/k_stone.webp','assets/k_look.webp','assets/k_sleep.webp','assets/k_wk1.webp','assets/k_wk2.webp','assets/k_wk3.webp','assets/k_wk4.webp','assets/k_wk5.webp','assets/k_wk6.webp','assets/k_wk7.webp','assets/k_wk8.webp','assets/k_sd1.webp','assets/k_sd2.webp','assets/k_sd3.webp','assets/k_sd4.webp','assets/k_j1.webp','assets/k_j2.webp','assets/k_j3.webp','assets/k_j4.webp','assets/k_j5.webp','assets/k_j6.webp','assets/k_j7.webp','assets/k_j8.webp','assets/k_w1.webp','assets/k_w2.webp','assets/k_w3.webp','assets/k_w4.webp','assets/k_blink.webp'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(F.map(u=>new Request(u,{cache:'reload'})))));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==location.origin)return;
 const fresh=e.request.mode==='navigate'||/\.html$|\/$/.test(u.pathname)?new Request(e.request.url,{cache:'no-store'}):e.request;
 // 그림(assets/)은 캐시 먼저 — 버전(C)을 올리면 새로 받는다
 if(u.pathname.includes('/assets/')){e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(r=>{if(r.ok){const c=r.clone();caches.open(C).then(x=>x.put(e.request,c))}return r})));return}
 e.respondWith(fetch(fresh).then(r=>{if(r.ok){const c=r.clone();caches.open(C).then(x=>x.put(e.request,c))}return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match('index.html'))))});
self.addEventListener('push',e=>{let d={title:'하루',body:''};try{d=e.data.json()}catch(x){d.body=e.data?e.data.text():''}
 e.waitUntil(self.registration.showNotification(d.title||'하루',{body:d.body,icon:'icon-180.png',badge:'icon-180.png',tag:'haru-'+Date.now()}))});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(l=>{for(const c of l)if('focus' in c)return c.focus();return clients.openWindow('./')}))});
